<Project>

	<!-- Import a Directory.Build.props file located in the parent directory -->
	<Import Project="$(MSBuildThisFileDirectory)./Directory.Build.props" />

	<PropertyGroup>
		<WarningsAsErrors>Nullable</WarningsAsErrors>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>

		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<Authors>X-Hax</Authors>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageIcon>SA3D-Icon.png</PackageIcon>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>

	</PropertyGroup>

	<ItemGroup>
		<None Include="$(MSBuildThisFileDirectory)LICENSE">
		  <Pack>True</Pack>
		  <PackagePath>/</PackagePath>
		</None>
		<None Include="$(MSBuildThisFileDirectory)SA3D-Icon.png">
		  <Pack>True</Pack>
		  <PackagePath>/</PackagePath>
		</None>
	  </ItemGroup>

</Project>